spring.application.name=api_simple_transfer
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.datasource.url=jdbc:h2:mem:api_simple_transfer
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always

#servico autorizacao transferencia
authorization.url=https://util.devi.tools/api/v2/authorize

# Esconde o campo 'trace' gigante do JSON de resposta
server.error.include-stacktrace=never

# Mostra a mensagem do erro
server.error.include-message=always